### ISSUE TITLE
Scripted test to upload a file and check th

### ISSUE THREAD

**Issue by rufuspollock** [datopian/aircan#100]
When developing AirCan i want a scripted test I can run to test the end to end functioning of a load of data into DataStore

## Acceptance

* [ ] Create a dataset in CKAN test instance
* [ ] Create resource with a file (link out to file online e.g. in github or in storage)
* [ ] Check on status of run using {ckan instance}/api/3/aircan_status
* [ ] Check datastore is updated (called data API): ... /api/3/datastore_search ...

## Tasks

...
