### ISSUE TITLE
Mocks for library

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#15]
When I work on AirCan as a developer, I want to be able to run the test suite without making network requests and using services that can be mocked instead so that I can test more effectively without depending on external resources.

## Acceptance

* [x] All the Python functions in `lib/load.py` are mocked in the test suite and can be run independently from external resources.

## Tasks

* [x] Mock `delete_datastore_table`.
* [x] Mock `create_datastore_table`.
* [x] Mock `load_csv_to_postgres_via_copy`.
* [x] Mock `delete_index`.
* [x] Mock `restore_indexes_and_set_datastore_active`.
* [x] Mock `_generate_index_name`.

## Analysis

* See if mocking `lib/api_ckan_load.py` and `examples/csv_to_json.py` is also useful for now.
* The functions in `load.py` are using the CKAN API. Comment present:
  > This should work over API (not inside CKAN process) or do direct
* This may be useful to mock `lib/api_ckan_load.py`: https://github.com/ckan/ckan/tree/master/ckan/tests

**Comment by shubham-mahajan** [comment]
FIXED - PRs #41 resolves this issue.
