### ISSUE TITLE
Create classes for Errors and Response

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#20]
## Acceptance

- [x] Aircan lib code to be wrapped into a class file
- [x] Create default interface for errors 
- [x] Create default interface for response

## Tasks 

At this time our internal libraries handle errors and responses this way, for example `return {"success": False, "response": response.json()}`.

Ideally, we should create a proper class for exceptions, errors handling and responses, unifying the way the system behaves (in library level)

**Comment by hannelita** [comment]
#20 and #53 fix this issue
