### ISSUE TITLE
Deploy to GCP

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#23]
Do a trial deployment of aircan to GCP cloud composer

## Acceptance

* [x] Running on GCP cloud composer
* ~~[ ] Successful ingest to e.g. demo.ckan.org via that setup~~

## Tasks

- [x] Obtain access to GCP Composer
- [x] Investigate  GCP composer and get e.g. UI and CLI working - document learnings and specify adjustments
- [x] Deploy aircan
  - [x] Pack Aircan core lib into a Pypi library See #29 
  - [x] Deploy single node DAG #31
  - [x] Create a DAG that handles the remote flow #30
- [x] Update README (see #37 )

Extras

- [x] Discuss Auth options  (Airflow Auth). Start with basic auth from airflow #32

**Comment by hannelita** [comment]
General Comments
* Got a bit more familiar with Google Cloud Composer. 
* Tried to deploy Aircan as an app (on AppEngine) and tried to access the lib code on Aircan. Does not work.
* We'll probably need to pack it to a Pypi lib and insert it as a dependency on the composer instance (under the tab Pypi packages). We'll have to wrap the lib and fix the cross refernence files.
* I tried to deploy a hard-coded version of the single node DAG, getting rid of the several dependency errors I'd run into by having an external lib:
<img width="383" alt="Screen Shot 2020-06-18 at 23 11 03" src="https://user-images.githubusercontent.com/506426/85093001-09d15000-b1b9-11ea-8399-a0a02e0769e7.png">
Hooray! It is there, but it does not run anything.  I have no clue why

**Comment by hannelita** [comment]
After a long debug time, some progress. THe modified DAG runs. I'll paste the code here:

```python
# # Standard library imports
import logging
import time
import json
import ast
from datetime import datetime
import requests
from urllib.parse import urljoin
import hashlib
import pandas as pd

from airflow.models import Variable
from airflow.operators.python_operator import PythonOperator

import airflow
from airflow import DAG
from airflow.operators.bash_operator import BashOperator
from datetime import timedelta


def delete_datastore_table(data_resource_id, ckan_api_key, ckan_site_url):
    header = {'Authorization': ckan_api_key}
    try:
        response = requests.post(
            urljoin(ckan_site_url, '/api/3/action/datastore_delete'),
            headers=header,
            json={
                "resource_id": data_resource_id,
                'force': True
            }
        )
        if response.status_code == 200 or response.status_code == 404:
            logging.info('Table was deleted successfuly')
            return {"success": True}
        else:
            return response.json()
    except Exception as e:
        return {"success": False, "errors": [e]}


def create_datastore_table(data_resource_id, resource_fields, ckan_api_key, ckan_site_url):
    data_dict = dict(
        # resource={'package_id': 'my-first-dataset', 'name' : 'Test1'},
        resource_id=data_resource_id,
        fields=[
            {
                'id': f,
                'type': 'text'
            } for f in resource_fields],
        )
    data_dict['records'] = None  # just create an empty table
    data_dict['force'] = True
    try:
        response = requests.post(
            urljoin(ckan_site_url, '/api/3/action/datastore_create'),
            headers={'Authorization': ckan_api_key},
            json=data_dict
        )
        if response.status_code == 200:
            return {'success': True}
            logging.info('Table was created successfuly')
        else:
            return {"success": False, "response": response.json()}
    except Exception as e:
        return {"success": False, "errors": [e]}


class DatastoreEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime.datetime):
            return obj.isoformat()
        if isinstance(obj, decimal.Decimal):
            return str(obj)

        return json.JSONEncoder.default(self, obj)


def load_resource_via_api(ckan_resource_id, records, ckan_api_key, ckan_site_url):
    logging.info("Loading resource via API")
    try:
        request = {
           'resource_id': ckan_resource_id,
           'force': True,
           'records': records}

        url = urljoin(ckan_site_url, '/api/3/action/datastore_create')
        response = requests.post(url,
                      data=json.dumps(request, cls=DatastoreEncoder),
                      headers={'Content-Type': 'application/json',
                               'Authorization': ckan_api_key}
                      )
        if response.status_code == 200:
            resource_json = response.json()
            return {'success': True, 'response_resource': resource_json}
            logging.info('Table was created successfuly')
        else:
            return response.json()

    except Exception as e:
        return {"success": False, "errors": [e]}



def convert(input, output, **kwargs):
    print('Starting file conversion')
    df = pd.read_csv(input)
    df.to_json(output, orient='records')
    return {"success": True}



def full_load(resource_id, schema_fields, csv_input, json_output, **kwargs):
    logging.info('Deleting Datastore if exists')
    delete_datastore_table(resource_id, Variable.get('CKAN_SYSADMIN_API_KEY'), Variable.get('CKAN_SITE_URL'))
    logging.info('Invoking Create Datastore')
    data_resource_fields = ast.literal_eval(schema_fields)
    create_datastore_table(resource_id, data_resource_fields, Variable.get('CKAN_SYSADMIN_API_KEY'), Variable.get('CKAN_SITE_URL'))
    logging.info('Converting resources to json')
    convert(csv_input, json_output)
    logging.info('Loading CSV via API')
    try:
        with open(json_output) as f:
            records = json.load(f)
            return load_resource_via_api(
                resource_id, records, Variable.get('CKAN_SYSADMIN_API_KEY'), Variable.get('CKAN_SITE_URL'))
    except Exception as e:
        return {"success": False, "errors": [e]}


default_args = {
    'start_date': airflow.utils.dates.days_ago(0),
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
    'params': { 
        "resource_id": "58596a2d-b413-4cce-b662-d65a977bce3d",
        "schema_fields_array": [ "FID", "Mkt-RF", "SMB", "HML", "RF" ], 
        "csv_input": "/home/airflow/gcs/dags/r3.csv", 
        "json_output": "/home/airflow/gcs/dags/r4.json"
    }
}

dag = DAG(
    'ckan_api_load_single_step',
    default_args=default_args,
    description='liveness monitoring dag',
    schedule_interval=None,
    dagrun_timeout=timedelta(minutes=60))


full_load_task = PythonOperator(
    task_id='full_load_via_api',
    provide_context=True,
    depends_on_past=False,
    python_callable=full_load,
    op_kwargs={'resource_id': "{{ params.resource_id }}", 'schema_fields': "{{ params.schema_fields_array }}", 'csv_input': "{{ params.csv_input }}", 'json_output': "{{ params.json_output }}" },
    dag=dag
)


```

This DAG sends data to dem.ckan: https://demo.ckan.org/dataset/another-cool-ds/resource/58596a2d-b413-4cce-b662-d65a977bce3d

Remarks:
* We will have to change the way we convert CSV to JSON. At this time I am using pandas and sending a location to dump the JSON contents to a son file. This doe snot work for GCP. We'll have to add another step creating the remote resource on a bucket. May also require a /tmp/ write for the JSON conversion.

* As addressed before, we will have to wrap all the lib code into a pypi lib. 

* It is certainly much better for the logs if we can run the multiple-node-DAG version. Also much better for retry. 

\cc @rufuspollock

**Comment by rufuspollock** [comment]
@hannelita great work 👏  Any reason we are using pandas vs simple csv lib (and can we not stream in process vs dump to a /tmp/ file?

**Comment by hannelita** [comment]
@rufuspollock No particular reason for Pandas. I personally think it is a good option (with fewer lines of code), since it does all the work or iterating through the column and converting into records automatically.

**Comment by hannelita** [comment]
Appending to my previous observation: Pandas works fine as long as we have a resource on GCP (i.e. the code calls it `r4.json`). Same scenario for `csv` lib. So we'll need to add a step t create the empty file on the cloud before converting it

**Comment by hannelita** [comment]
After digging a bit more into the docs, I found a way to input library code into Google Cloud composer *without* using a Pypi package. Note: This is not a clean way to do it! Certainly having a Pypi package is the ideal. Meanwhile, by renaming the `lib` folder to dependencies and making the import adjustments on the file, we can simply copy the `aircan` folder to GCP, remove the `__init__` file on the DAG (it conflicts with other internal files on Composer) and voilà! The provider will recognize the DAGs without a Pypi package.

**Comment by hannelita** [comment]
PRs #32 and #37 fix this issue
