### ISSUE TITLE
Pack Aircan core lib into a Pypi package

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#29]
Packing the code into a PyPI package is necessary to have Aircan running into a cloud provider (GCP).

## Acceptance

- [x] Pypi package `aircan-lib` deployed and possible to install via requirements.txt
- [x] Local DAGs refactored to use the new package

## Tasks

* [ ] (?) Boot a  new repo (may not be deleted) https://github.com/datopian/aircan-lib
* [x] Factor our library code (with tests) to a new repo
* [x] Publish to PyPI and make Datopian an owner

## Analysis

**Comment by hannelita** [comment]
https://pypi.org/project/aircan/; project deployed to pypi and at this time the DAGs and the lib code are on the same project.

**Comment by hannelita** [comment]
Note: we did not have the discussion about splitting the DAGs and the lib into different projects. For development, it can be handy to use the process I described here https://github.com/datopian/aircan/issues/23#issuecomment-648565241 , esp because it takes some time to GCP locate new pypi packages.

**Comment by shubham-mahajan** [comment]
@hannelita We need to update the readme or new to create a new readme for PyPI, it is breaking there and actually don't reflect what package will do.

**Comment by hannelita** [comment]
Fixed with #29
