### ISSUE TITLE
Create a multiple node DAG for GCP

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#30]
Using the same structure of the multiple node DAG assuming local files, create a DAG that handles resources on the cloud (CSV and JSON). 

## Acceptance

- [ ] DAG with multiple nodes doing the entire pipeline on GCP.

## Tasks
- [X] Use aircan from Pypi
- [ ] Refactor code to reuse existing nodes

DAG tasks:
- [X] 1. ~Upload CSV from CKAN instance to bucket~ Read remote CSV
- [X] 2. delete_datastore
- [X] 3. create_datastore
- [X] 4. Creake JSOn file on bucket
- [X] 5. convert_csv_to_json
- [x]  6. Send converted JSON file to CKAN

~~ckannext-aircan (connector) tasks:~~
~~- [x] 1. create endpoint to receive Airflow response after processing~~
~~- [x] 2. Handle Airflow response~~
~~- [ ] 3. If success, download processed json file from bucket~~

*NOTE*: This is not the strategy. We will send the processed JSON via API.

<img width="468" alt="Screen Shot 2020-07-13 at 07 33 35" src="https://user-images.githubusercontent.com/506426/87300087-3b4ceb00-c4db-11ea-9faa-1c6335e0a139.png">

## Analysis

After this long task is complete, we still need to:
~~- [ ] Handle errors~~ This will be in the next milestone
~~- [ ] Handle absence of a response from Airflow~~ This will be in the next milestone
~~- [ ] Delete remote file (create a separate DAG for that)~~ This will be in the next milestone

**Comment by hannelita** [comment]
Before everything, try to specify remote file locations for csv and json

**Comment by hannelita** [comment]
Remote CSV fetching works

**Comment by hannelita** [comment]
Problem with enoding when reading remote file on Airflow DAG

**Comment by hannelita** [comment]
Resolved with #53
