### ISSUE TITLE
Authenticate user on Airflow web interface (GCP)

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#32]
We want to allow authenticated users only on the airflow GCP webserver.

## Acceptance
- [x] Only authenticated users can login.
- [x] Using https://github.com/datopian/ckanext-aircan, properly invoke a DAG running on GCP

## Tasks
- [x] Enable basic auth
- [x] After #42 is done, check any other requirements for this task
- [x] On ckanext-aircan, establish a distinction between a  local airflow instance and an instance on the cloud (GCP)
- [x] Obtain a GCP client from ckanext-aircan
- [x] Authenticate Client
- [x] Parameterize DAG name and invoke DAG on GCP via Airflow API

## Analysis
~Discuss other authentication methods rather than basic auth.~ By setting the security configuration, it is possible to allow only specific users, or groups of users, etc. Much stronger than basic HTTP Auth. In this version, we'll use Google Auth, which requires a token

**Comment by hannelita** [comment]
@rufuspollock I enabled IAM Authentication and I think https://b011229e45c662be6p-tp.appspot.com is not public anymore. Is there any other type of authentication we should try?

**Comment by hannelita** [comment]
ATM Blocked by #42

**Comment by hannelita** [comment]
In https://github.com/datopian/ckanext-aircan/pull/3, it is possible to trigger a DAG via ckanext-aircan connector
This PR fixes this issue
