### ISSUE TITLE
Update and organize the README after recent changes

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#37]
After #8 and all the changes on the new DAGs, it is necessary to update the README file to reflect the most recent status of the project. 

## Acceptance
- [x] User must successfully replicate described steps and install aircan locally
- [x] User must successfully run example DAG
- [x] User must run single_node_dag locally
- [x] User must run multiple_node DAG successfully
- [x] User must set up composer successfully with the two previous DAGs

## Tasks
- [x] Cleanup general install instructions
- [x] Separate sections more clearly (setup + run example / Local aircal ( single node DAG / multiple node DAG) / remote aircan on GCP
- [x] Provide section for GCP
