### ISSUE TITLE
Moving data out of dags directory to data directory

### ISSUE THREAD

**Issue by shubham-mahajan** [datopian/aircan#43]
As an aircan user, I want to separate the data directory from the dags directory so that import of dags will be lightweight and data can be accessed outside the code.

## Acceptance

* [ ] ~~Data should be accessible from dags~~

## Tasks

* [ ] ~~Separate the Data and Dags~~
* [ ] ~~Make data accessible in dags~~

**Decided to delete the sample files from Dag.**
