### ISSUE TITLE
Build a DAG that loads a file to CKAN using DB connection

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#5]
Build a DAG that loads a file to CKAN ( remote demo.ckan) using DB connection

## Acceptance

- Run this DAG from a local airflow instance and have a file loaded on remote CKAN

...

## Tasks

- [ ] Check https://gitlab.com/datopian/tech/data-loader-next-gen/-/blob/master/data_loader/load.py
- [ ] Copy over relevant parts (+ tests) into local `/lib/` folder
- [ ] Create appropriate airflow tasks + DAG using this lib methods: **~rufus debatable if this is worth it** 
```python
delete_datastore_table <<
    create_datastore_table <<
    load_csv_to_postgres_via_copy <<
    restore_indexes_and_set_datastore_active
```

**Comment by hannelita** [comment]
Closing this for now; focusing on #9
