### ISSUE TITLE
make test command returning an error

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#50]
## acceptance
- [x] `make test` should run clean and all tests related to API integration should pass.

## Tasks and description

After the refactor from lib to dependencies, some tests have imports outdated .

PR #51  adds some fixes; we still need to

- [x] Add instruction on READme about `make test`
- [x] fix api-related tests; I believe it's missing an .env file

**Comment by hannelita** [comment]
Fixed with #50
