### ISSUE TITLE
Cypress testing

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#59]
## Acceptance 
- [x] Test suite on Cypress 

## Tasks
- [x] Test resource_create and validate whether resource is created
- [x] Test whether UI have the `Data Dictionary` and other details in the resource
- [x] Test datastore is having the details of the ingested data
- [ ] ~~Test datastore create~~
- [ ] ~~Test datastore delete~~

**Comment by shubham-mahajan** [comment]
fixed by https://github.com/datopian/ckanext-aircan/pull/11
