### ISSUE TITLE
[Refactor] DAGs

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#60]
## Acceptance

- [x] Receive a description JSON file and obtain resource info (file and fields) from there
- [x] Pass CKAN env info when triggering DAG
- [x] No duplicate tasks for the multiple DAGs we have
- [x] Organize DAGs in subdirectories

## Tasks

Relates to #30

**Comment by hannelita** [comment]
Several PRs #71, #83 and ckannext-aircan #9 solve this issue.
Note: It would be good to have a DAG refactor task from time to time
