### ISSUE TITLE
Refactor - DAG Payload on Aircan Connector

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#61]
## Acceptance
- [ ] Using CKAN API, upload a resource and pass enough information to trigger the DAG with:
```javascript
"conf": {
  resource: {  // a f11s data resource object
    "path": ckan_resource['url'],
    "format": ckan_resource['format'],
    "ckan_resource_id": ckan_resource['id'],
    "schema": ckan_resource['schema']
  }
  "ckan_config": {
    "api_key": ..
  }
}
```

~Note: Airflow does not support nested JSON; we'll have to send the info in a one-level json ~
*Note2*: When using JINJA templates, it doesn't. When fetching params from `**context`, it works, so we're adopting the original proposal

```
"conf": {
    "path": ckan_resource['url'],
    "format": ckan_resource['format'],
    "ckan_resource_id": ckan_resource['id'],
    "schema": ckan_resource['schema']
    "ckan_api_key": ..
}
```

## Tasks

- [x] Refactor gcp DAG to receive `**context` as it's only arg
- [x] Update action.py on Aircan connector
- [x] Update README
- [ ] ~Update schema key to receive a f11ys~ See #72

**Comment by hannelita** [comment]
Docs on https://github.com/datopian/ckanext-aircan/pull/13. This PR and #71  fix this issue
