### ISSUE TITLE
Logs from GCP on CKAN

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#69]
## Acceptance
- [x] In the dag_status endpoint on CKAN-aircan connector, we should receive logs/info from the remote Airflow DAG run on GCP

## Tasks
- [x] Google CLoud logging API integration https://cloud.google.com/logging/docs/reference/libraries#cloud-console 
- [x] Enable appropriate StackDriver support [properly updated on Aircan-connector README]
- [x] Create Sink for collecting logs
- [x] Adjust Credentials for Logging API (not the same client used for triggering a DAG)
- [x] Consume logs from filtered entries

**Comment by hannelita** [comment]
Update: Still having troubles with Credentials

**Comment by hannelita** [comment]
4h to fix credentials (need to split credentials from general GCP)
