### ISSUE TITLE
/aircan_submit will take the DAG name

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#79]
## Acceptance

- [x] /aircan_submit endpoint will take the DAG name
- [x] Response gives dag_run id

## Tasks
- [x] Endpoint refactor
- [x] GCP calls refactor
- [x] Endpoint returns DAG run id in its reponse
- [x] Update Docs

**Comment by hannelita** [comment]
```
{
    "execution_date": "2020-07-31T01:24:44+00:00",
    "message": "Created <DagRun ckan_api_load_multiple_steps @ 2020-07-31 01:24:44+00:00: manual__2020-07-31T01:24:44+00:00, externally triggered: True>",
    "run_id": "manual__2020-07-31T01:24:44+00:00"
}
```

**Comment by hannelita** [comment]
datopian/ckanext-aircan#14 Fixes this issue
