### ISSUE TITLE
[epic][uber] v1 of CKAN DataStore Load using AirCan

### ISSUE THREAD

**Issue by rufuspollock** [datopian/aircan#85]
* v0.1 MVP DataStore load working including
  * [ ] Staging environment: AirCan (Google Cloud Composer) + CKAN instance with extension **80% Deployed but issues with Solr: https://gitlab.com/datopian/tech/devops/-/issues/206 and https://github.com/datopian/aircan/issues/66**
  * [x] CI working **Passing tests**
  * [ ] Integration tests of DataStore Load (in cypress) e.g. we upload a file to CKAN staging instance and 5m later data is in datastore. **We have the tests, but they are assuming a local `npm test`. Right now they are pointing to a temporary CKAN instance (not to DX) and they run the entire flow. No CI for this on github atm**
  * [ ] CD of AirCan and CKAN extension into staging (includes terraform setup of GCC) **...**
  * [ ] BONUS: BigQuery DAG for NHS **TODO: state of this**
* v0.2 - errors and logging
* v0.3 - UI integration into CKAN
* v0.4 - improved datastore load e.g. more formats
  * [ ] Loads XLSX ok (uses types)
  * [ ] Load google sheets
* v0.5 - harvesting MVP

```mermaid
graph TD

v1[v0.1 CSV load working, CI/CD setup with rich tests]
v2[v0.2 errors, logging and UI integration]
v3[UI integration]
v3[v0.3 expand the tasks and  e.g. xlsx, google sheets loading]
v4[v0.4 harvesting ...]


v1 --> v2
v2 --> v3
v3 --> v4
```

### Detailed

```mermaid
graph TD

deploytotest[Deploy DAGs to test GCC]
deploydags[Deploy DAGs into this AirFlow<br/>starting with CKAN data load]
deploygcc[Deploy Airflow<br/>i.e. Google Cloud Composer]

nhsdag[NHS DAG for loading to bigquery]
nhs[NHS Done: instance updated<br/>with extension and working in production]

logging[Logging]
reporting[Reporting]

othersite["Other Site Done"]

start[Start] --> deploygcc

start --> logging
multinodedag --> deploytotest

subgraph General Dev of AirCan
  errors[Error Handling]
  aircanlib[AirCan lib refactoring]
  multinodedag[Multi Node DAG]
  logging --> reporting
end

subgraph Deploy into Datopian Cluster
  deploytotest[Deploy DAGs to test GCC] --> deploydags
  deploygcc --> deploydags
end

subgraph CKAN Integration
  setschema[Set Schema from Resource]
  endckan[End CKAN work]
  setschema --> endckan
end

deploydags --> nhsdag
deploydags --> othersite
endckan --> nhs

subgraph NHS
  nhsdag --> nhs
end

classDef done fill:#21bf73,stroke:#333,stroke-width:1px;
classDef nearlydone fill:lightgreen,stroke:#333,stroke-width:1px;
classDef inprogress fill:orange,stroke:#333,stroke-width:1px;
classDef next fill:lightblue,stroke:#333,stroke-width:1px;

class multinodedag done;
class versioning nearlydone;
class setschema,errors,deploydags,nhsdag,deploygcc inprogress;
```

**Comment by rufuspollock** [comment]
@hannelita can you update this with current state.
