### ISSUE TITLE
Refactor to have aircan_submit API and resource_create hook

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#88]
## Acceptance
- [x] Support both endpoints
- [x] resource_submit takes local env var
- [x] Aircan submit takes URl param

## Tasks
- [x] Refactor existing action to make distinction
