### ISSUE TITLE
Migrate datastore-next-library code to this repo

### ISSUE THREAD

**Issue by hannelita** [datopian/aircan#9]
## Acceptance

- [x] previous datahub-next-loader code into lib/ folder
- [x] DAG file invoking loader
- [ ] ~Mocks~ Moved to #15 

## Tasks

- [x] Copy over existing datastore loader code from https://gitlab.com/datopian/tech/data-loader-next-gen
- [x] Create invoking operator for each task individually and making sure they run properly
    - [x] delete_datastore_table
    - [x] create_datastore_table
    - [x] load_csv_to_postgres_via_copy 
- [ ] ~Create mocks for existing functions~ See #15

### Questions

* On `load_csv_to_postgres_via_copy`, we'll probably need a refactor, since it returns a generic error 
```
except Exception as e:
                    return {
                        'success': False,
                        'message': 'Error during deleting index: {}'.format(e)
                    }
```

* The original library uses .env vars. Here I'm switching to airflow vars. Pros: Easy to manage everything in airflow UI; cons: code will be tied to airflow; there is a simple way to refactor it and make it entirely agnostic \cc @rufuspollock

**Comment by rufuspollock** [comment]
> The original library uses .env vars. Here I'm switching to airflow vars. Pros: Easy to manage everything in airflow UI; cons: code will be tied to airflow; there is a simple way to refactor it and make it entirely agnostic \cc @rufuspollock

Sounds good.

**Comment by hannelita** [comment]
Remarks:
* Testing on a local CKAN and on demo.ckan is not the same. With a local instance, I managed to get access to a postgres and understand the flow. Not sure how to do that for demo.ckan.
* Every datastore table comes with `_id` and `_full_text` fields. Fun fact: the COPY command for the CSV was throwing errors because it takes these two fields into consideration when parsing. This needs to be fixed.
* We need better error messages/error handling
* Work on a better var config system, as addressed in #10

**Comment by rufuspollock** [comment]
@hannelita there is no way to do direct to DB load on demo.ckan.org (that won't be possible).

**Comment by rufuspollock** [comment]
FIXED. All done - see description and moved mocks to #15
